{
  "comments": [
    {
      "key": {
        "uuid": "2a4207f0_be58b3ee",
        "filename": "applications/common/src/main/java/org/onap/policy/pdp/xacml/application/common/TestUtils.java",
        "patchSetId": 4
      },
      "lineNbr": 64,
      "author": {
        "id": 57
      },
      "writtenOn": "2019-04-11T01:18:47Z",
      "side": 1,
      "message": "Won\u0027t let me just add throws to the method. Have to try-catch it. Also cannot re-throw the exception. Weird.",
      "range": {
        "startLine": 59,
        "startChar": 1,
        "endLine": 64,
        "endChar": 1
      },
      "revId": "5325da667cbafdfb8c52913177a3e195734c9f8c",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "d695e5d4_245b8d36",
        "filename": "applications/common/src/main/java/org/onap/policy/pdp/xacml/application/common/TestUtils.java",
        "patchSetId": 4
      },
      "lineNbr": 64,
      "author": {
        "id": 811
      },
      "writtenOn": "2019-04-11T01:27:28Z",
      "side": 1,
      "message": "oh, puke, so much for using \"foreach\" in this case.  Yeah, the exception is being thrown by the functional object, not by loadPolicies, itself.  Unfortunately, \"foreach\" doesn\u0027t take functional objects that throw exceptions. :-(",
      "parentUuid": "2a4207f0_be58b3ee",
      "range": {
        "startLine": 59,
        "startChar": 1,
        "endLine": 64,
        "endChar": 1
      },
      "revId": "5325da667cbafdfb8c52913177a3e195734c9f8c",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    }
  ]
}